# Generated by Django 4.0.6 on 2022-07-21 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomproduit', models.CharField(max_length=200, null=True)),
                ('quantite', models.IntegerField(max_length=200, null=True)),
                ('prix', models.FloatField(max_length=200, null=True)),
                ('data_creation', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
